BcWork/Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView
from Litomici_memeber_system import settings as STS

app_name = 'account'
urlpatterns = [
    #administration
    path("showMembers&Accounts",views.showMembers, name="showMembers"), # type: ignore
    path("semberDetail/<str:member_id>",views.memberDetail,name="memberDetail"), # type: ignore
    path("payment",views.seeMoney,name="payment"),
    path("economy",views.unpayed_payments,name="economy"),
    path("bankTransactions",views.bank_transactions,name="bankTransactions"),
    path("payed",views.payed_payments,name="payed"),
    path("payments",views.payments,name="payments"),
    path("notify2pay/<str:account_id>",views.notify2pay,name="notify2pay"),
    path("addMoney2pay/<str:account_id>",views.addMoney2pay,name="need2pay"),
    path("manualPayment",views.manual_payment,name="manualP"),
    path("maunalDown",views.download_pdf,name="getManual"),
    #sending an email
    path("sendNotification/<int:action_id>/<int:event_id>",views.sendNotification,name="sendEmail"),#type: ignore
    path("sendMsg",views.sendMessage,name="sendMSG"),#simple message from user
    path("addNewUser",views.addUserToAccount,name="addNewUser"),#adding new user to account # type: ignore
    path("setPassword/<str:token>/",views.invitedUser,name="setPasswd"),
    #account operations
    path("account",views.userIn, name="logged"),
    path("profileInfo",views.userData, name="profile"),
    path("removeMember",views.removeMember,name="removeMemeber"),
    path("addMember",views.add_member_to_account,name="addMember"),
    path("changeData", views.changeData, name="changeData"),
    #creating new entity
    path("register",views.signUp, name="signUp"),
    path('newAccount',views.NewAccount, name='newAccount'),
    path("addEvent",views.userData, name="addEvent"),
    path("createMemeber",views.newMember,name="newMember"),
    #loging
    path("login",views.signIn, name="login"),
    path("logout",LogoutView.as_view(next_page=STS.LOGOUT_REDIRECT_URL), name="logout"),
    #password reset 
    path('password_reset/', PasswordResetView.as_view(template_name='registration/resetPass.html',from_email='turistaklitomici@gmail.com', html_email_template_name='registration/password_reset_email.html',email_template_name='registration/password_reset_email.html',success_url="done"), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='registration//password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #errors
    path("",views.signIn, name="404"),
    #development only 
    # path("test",views.tester,name="test"),
    # path("testF",views.testF,name="testF"),
    

]

BcWork/Events/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView


app_name = 'event'
urlpatterns = [
    path("listAll/<int:event_id>/",views.listAll,name="listAll_id_add"),
    path("listAll",views.listAll,name="listAll"),
    path("details/<int:event_id>/",views.details,name="details"),
    path("listCamps",views.listCamps,name="listCamps"),
    path("campRegister/<int:event_id>",views.campReg,name="campRegister"), # type: ignore
    path("eventTool",views.eventActions,name="tool"), # type: ignore
    path("eventTool/create",views.eventActionsCreate,name="tool-create"),
    path("eventTool/edit",views.eventActionEdit,name="tool-edit"),
    path("eventTool/attendance",views.eventActionAttendace,name="tool-attendace"),
    path("eventTool/attendanceOfEvent/<int:event_id>/",views.eventActionAttendace2Event,name="tool-attendace2Event"),
    path("eventTool/cancel",views.eventActionCancle,name="tool-cancel"),
    path("eventTool/cancelOfEvent/<int:event_id>",views.cancelingOfEvent,name="tool-cancelOfEvent"),#type: ignore
]

BcWork/Litomici_memeber_system/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from Accounts import urls
from Events import urls

urlpatterns = [
    path('admin/', admin.site.urls,),
    path("",include("Accounts.urls")),
    path("event/",include("Events.urls")),
]

BcWork/templates/BlindPath.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/general.css' %}">
        <link rel="stylesheet" href="{% static 'css/login.css'%}">
    </head>
    <body>
        <header>
            <div class="headline"><h1>Localhost 8000</h1><br>
            <h2></h2></div>
        </header>
        <main>
            <h1>Seznam projektů</h1>
            <ul>
                <li><a href="login">ORG-system</a></li>
                <li><a href="admin">testy</li>
                    <li><a href="/logout"><button type="button" class="btn btn-light">Odhlásit se</button></a></li>
                </ul>
        </main>
        <footer>
            <div>
                
            </div>
        </footer>
        
        <script src="" async defer></script>
    </body>
</html>

BcWork/templates/blindPath.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/general.css' %}">
        <link rel="stylesheet" href="{% static 'css/login.css'%}">
    </head>
    <body>
        <header>
            <div class="headline"><h1>Localhost 8000</h1><br>
            <h2></h2></div>
        </header>
        <main>
            <h1>Seznam projektů</h1>
            <ul>
                <li><a href="login">ORG-system</a></li>
                <li><a href="admin">testy</li>
                    <li><a href="/logout"><button type="button" class="btn btn-light">Odhlásit se</button></a></li>
                </ul>
        </main>
        <footer>
            <div>
                
            </div>
        </footer>
        
        <script src="" async defer></script>
    </body>
</html>

BcWork/templates/index.html
{% extends "tags/foundations/notLoggedFoundation.html" %}
{%block main%}
<main>
    <div class="banner">
    
    </div>
    
    <div class="login">
    <form action="/login" method="post" class="logging">
        {% csrf_token %}
        <h1>Přihlaste se</h1>
        <label for="mail">Emailová adresa:</label>
        <input type="text" class="data" name="mail" id="mail" placeholder="email" required ><br>
        <label for="mail">Heslo: </label>
        <input type="password" class="data" name="pass" id="pass" placeholder="password" required><br>
        {% for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
        <input type="submit" class="submit btn-primary" value="Přihlásit"><br>
        <div class="log-questions">
            <p>Nemáš účet?<a href="{% url "account:signUp" %}">Zaregistruj se </a></p>
            <br> <p> Zapomněl jsi heslo? <a href="{% url "account:password_reset" %}">Zapomenuté heslo</a></p>
        </div>
    </form>
    </div>
    
</main>
{% endblock %}

BcWork/templates/resetPass.html
<!DOCTYPE html>
{%load static%}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
       <!-- <link rel="stylesheet" href="../static/css/login.css">
        <link rel="stylesheet" href="../static/css/general.css">-->
       <link rel="stylesheet" href="{% static 'css/general.css'%}">
        <link rel="stylesheet" href="{% static 'css/login.css'%}">
    </head>
    <body>
        <header>
            <img src="{% static 'img/whiteLogoNoBG.png' %}"><br>
            <div class="headline"><h1>Litomcamp</h1><br>
            <h2>Rozvíjej své dovednosti naplno</h2></div>
        </header>
        <main>
            <div class="banner">
            
            </div>
            
            <div class="login">
                <h1>Obnov si heslo blbecku</h1>
            <form action="/reset" method="post">
                {% csrf_token %}
                <label for="mail">Vaše emailová adresa:</label><br>
                <input type="text" class="data" name="mail" id="mail" placeholder="email" required ><br>
                {% for message in messages %}
                <p><b>Chyba při zasílání obnovovacího odkazu: </b>{{message}}</p>
                {% endfor %}
                <input type="submit" class="submit" value="Obnovit heslo">
                
            </form>
            </div>
            
        </main>
        <footer>
            <div>
                <h3>Turistický oddíl mládeže Čr LITOMÍCI č.oddílu: 21205</h3><br>
                <p>
                    Dukelské kasárny, Na Vinici<br>
                    412 01 Litoměřice, Česká republika, EU<br>
                    <br>
                    tel. +420 702 210 101<br>
                    tel. +420 776 469 914<br>
                    turistaklitomici@gmail.com
                </p>
            </div>
        </footer>
        
        <script src="" async defer></script>
    </body>
</html>

BcWork/templates/test.html
{% extends "tags/foundations/LoggedUserFoundation.html" %}
{%block main%}
    {% include "tags/pageComponents/sideNavbar.html" %}
    <div class="content">
    {% block Content %}
    <h2>Přidejsi členy tohoto účtu</h2>
  <form method="post" action='/addMember'>
    {% csrf_token %}
    <label for="member_id">Select a Member:</label>
    <select name="member_id" id="member_id">
      {% for member in available_members %}
        <option value="{{ member.id }}">{{ member.jmeno }} {{ member.surname }}</option>
      {% endfor %}
    </select>
    <button type="submit">Přidat zvoleného člena</button>
  </form>
  <h3>Nenašli jste člena v seznamu členů? Přidejte ho ručně. <a href="/createMemeber"><button>Vytvořit nového člena</button></a>
    {% endblock %}
</div>
{% endblock %}

BcWork/templates/test2.html
<<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>test</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h2> Vytvořeno</h2>
        {{tmp}}
        <script src="" async defer></script>
    </body>
</html>