BcWork/Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView
from Litomici_memeber_system import settings as STS

app_name = 'account'
urlpatterns = [
    #administration
    path("showMembers&Accounts",views.showMembers, name="showMembers"), # type: ignore
    path("semberDetail/<str:member_id>",views.memberDetail,name="memberDetail"), # type: ignore
    path("payment",views.seeMoney,name="payment"),
    path("economy",views.unpayed_payments,name="economy"),
    path("bankTransactions",views.bank_transactions,name="bankTransactions"),
    path("payed",views.payed_payments,name="payed"),
    path("payments",views.payments,name="payments"),
    path("notify2pay/<str:account_id>",views.notify2pay,name="notify2pay"),
    path("addMoney2pay/<str:account_id>",views.addMoney2pay,name="need2pay"),
    path("manualPayment",views.manual_payment,name="manualP"),
    path("maunalDown",views.download_pdf,name="getManual"),
    #sending an email
    path("sendNotification/<int:action_id>/<int:event_id>",views.sendNotification,name="sendEmail"),#type: ignore
    path("sendMsg",views.sendMessage,name="sendMSG"),#simple message from user
    path("addNewUser",views.addUserToAccount,name="addNewUser"),#adding new user to account # type: ignore
    path("setPassword/<str:token>/",views.invitedUser,name="setPasswd"),
    #account operations
    path("account",views.userIn, name="logged"),
    path("profileInfo",views.userData, name="profile"),
    path("removeMember",views.removeMember,name="removeMemeber"),
    path("addMember",views.add_member_to_account,name="addMember"),
    path("changeData", views.changeData, name="changeData"),
    #creating new entity
    path("register",views.signUp, name="signUp"),
    path('newAccount',views.NewAccount, name='newAccount'),
    path("addEvent",views.userData, name="addEvent"),
    path("createMemeber",views.newMember,name="newMember"),
    #loging
    path("login",views.signIn, name="login"),
    path("logout",LogoutView.as_view(next_page=STS.LOGOUT_REDIRECT_URL), name="logout"),
    #password reset 
    path('password_reset/', PasswordResetView.as_view(template_name='registration/resetPass.html',from_email='turistaklitomici@gmail.com', html_email_template_name='registration/password_reset_email.html',email_template_name='registration/password_reset_email.html',success_url="done"), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='registration//password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #errors
    path("",views.signIn, name="404"),
    #development only 
    # path("test",views.tester,name="test"),
    # path("testF",views.testF,name="testF"),
    

]

BcWork/Events/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView


app_name = 'event'
urlpatterns = [
    path("listAll/<int:event_id>/",views.listAll,name="listAll_id_add"),
    path("listAll",views.listAll,name="listAll"),
    path("details/<int:event_id>/",views.details,name="details"),
    path("listCamps",views.listCamps,name="listCamps"),
    path("campRegister/<int:event_id>",views.campReg,name="campRegister"), # type: ignore
    path("eventTool",views.eventActions,name="tool"), # type: ignore
    path("eventTool/create",views.eventActionsCreate,name="tool-create"),
    path("eventTool/edit",views.eventActionEdit,name="tool-edit"),
    path("eventTool/attendance",views.eventActionAttendace,name="tool-attendace"),
    path("eventTool/attendanceOfEvent/<int:event_id>/",views.eventActionAttendace2Event,name="tool-attendace2Event"),
    path("eventTool/cancel",views.eventActionCancle,name="tool-cancel"),
    path("eventTool/cancelOfEvent/<int:event_id>",views.cancelingOfEvent,name="tool-cancelOfEvent"),#type: ignore
]

BcWork/Litomici_memeber_system/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from Accounts import urls
from Events import urls

urlpatterns = [
    path('admin/', admin.site.urls,),
    path("",include("Accounts.urls")),
    path("event/",include("Events.urls")),
]

BcWork/Accounts/forms.py
from django.forms import DateTimeInput, ModelForm
from django import forms
from django.core.exceptions import ValidationError
import re
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

def validate_mobile_number(value):
    allowed_chars = set("0123456789+")
    if not set(value).issubset(allowed_chars):
        raise ValidationError("Nedovolené znaky v telefoním čísle.")
def validate_psc_number(value):
    allowed_chars = set("0123456789 ")
    if not set(value).issubset(allowed_chars):
        raise ValidationError("nesprávné znaky v PSC")
def validate_alpha_characters(value):
    regex_pattern = r'^[a-zA-ZěščřžýáíéťďňúůüĚŠČŘŽÝÁÍÉŤĎŇÚŮÜ ,.\-\']+?$'

    # Kontrola řetězce pomocí regulárního výrazu
    if re.match(regex_pattern, value):
        print("ok")
    else:
        raise ValidationError('Názvy měst mohou obsahovat pouze písmena české abecedy, mezery následující (,),(-),(.)')


class NewMemeberForm(ModelForm):
    class Meta:
        model = member
        fields = ['jmeno', 'surname', 'birthday','GDPR', 'healthProblems']
        labels={
            "jmeno": ('Jméno:'),
            "surname": ('Příjmení:'),
            "birthday":('Datum narození '),
            "GDPR": ('Souhlasím s tím, aby byly pořizovány a uchovávány fotografie a osobní údaje člena.'),
            "healthProblems": ('Zdravotní problémy a jiná důležitá omezení:'),
        }
        widgets={
            "jmeno": forms.TextInput(attrs={'class':'form-control form-control-lg','pattern': '^[A-Za-zÀ-ÖØ-öø-ÿĀ-žſ]+$'}),
            "surname": forms.TextInput(attrs={'class':'form-control form-control-lg','pattern': '^[A-Za-zÀ-ÖØ-öø-ÿĀ-žſ]+$'}),
            "birthday": forms.DateInput(attrs={'type': 'date','class':'form-control'}),
            "GDPR": forms.CheckboxInput(attrs={'class':'form-check-input','id':'checkbox'}),
            "healthProblems": forms.Textarea(attrs= {"class":"form-control", "id":"exampleFormControlTextarea1","rows":"3"}),
        }
class NewAccountForm(ModelForm):
    class Meta:
        model = Account
        fields = ['user','mobile1', 'addres1', 'city1', 'psc1','mobile2']
        labels={
            "user":(""),
            "mobile1": ('Telefon na rodiče nebo zákonného zástupce'),
            "addres1": ('Adresa bydliště'),
            "city1": ('Město'),
            "psc1": ('PSČ'),
            "mobile2":('Telefon na druhého rodiče nebo jiného člena rodiny')
        }
        widgets={
            "user": forms.TextInput(attrs= {'class':'form-control','readonly':'readonly'}),
            "mobile1": forms.TextInput(attrs={'class':'form-control'}),
            "addres1": forms.TextInput(attrs={'class':'form-control'}),
            "city1": forms.TextInput(attrs= {'class': 'form-control'}),
            "psc1": forms.TextInput(attrs= {'class': 'form-control'}),
            "mobile2":forms.TextInput(attrs= {'class': 'form-control'})
        }
        
class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields=["username","password1","password2"]
        widgets={
            "username": forms.TextInput(),
            "password1": forms.PasswordInput(),
            "password2": forms.PasswordInput(),
        }
        labels={
            "username": ('Emailová adresa'),
            "password1": ("Heslo"),
            "password2": ('Potvrzení hesla'),
        }
        help_texts = {
            "password1": "Heslo musí být 8 znaků dlouhé. Nesmí obsahovat pouze čísla nebo být seznamu snadno prolomitelných hesel.",
        }
class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    text = forms.CharField(widget=forms.Textarea)
    
class AddUserForm(forms.Form):
    newUserEmail = forms.EmailField(
        label="Email, kterému chcete umožnit přístup.",
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control mb-8'})
    )
class SetPasswordForm(forms.Form):
    password1 = forms.CharField(
        label="Heslo",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password2 = forms.CharField(
        label="Potvrzení hesla",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

class changeDataForm(forms.Form):
    mobile1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        validators=[validate_mobile_number]
        )
    addres1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        )
    city1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        validators=[validate_alpha_characters]
        )
    psc1 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        validators=[validate_psc_number]
        )
    state1 = forms.ChoiceField(
        choices=(
            ('', 'Vyberte'),
            ('Česko', 'Česko'),
            ('Slovensko', 'Slovensko'),
            ('Německo', 'Německo'),
            ('Polsko', 'Polsko'),
            ('jiné', 'jiné'),
        ),
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    mobile2 = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        validators=[validate_mobile_number]
        )
    addres2= forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
        )
    city2= forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        #validators=[validate_alpha_characters],
        required=False
        )
    psc2= forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        validators=[validate_psc_number],
        required=False
        )
    state2 = forms.ChoiceField(
        choices=(
            ('', 'Vyberte'),
            ('Česko', 'Česko'),
            ('Slovensko', 'Slovensko'),
            ('Německo', 'Německo'),
            ('Polsko', 'Polsko'),
            ('jiné', 'jiné'),
        ),
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=False
    )
class UploadFileForm(forms.Form):
    file = forms.FileField(label='Vyberte soubor',widget=forms.FileInput(attrs={'class': 'form-control','id':"fileInput"}))
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Nastavíme enctype na multipart/form-data
        self.fields['file'].widget.attrs.update({'enctype': 'multipart/form-data'})

BcWork/Events/forms.py
from django.forms import DateTimeInput, ModelForm
from django import forms
from .models import Event

class EventCreationForm(ModelForm):
    class Meta:
        model = Event
        fields = ['organizedBy','event_type','name', 'destination', 'meeting', 'ending', 'departure', 'arrival', 'notes','capacity','travel','price','description']
        labels={
            "event_type":('Typ akce'),
            "name": ('Název Události'),
            "destination": ('Cíl cesty/Místo konání'),
            "meeting": ('Datum a čas srazu'),
            "ending": ('Datum a čas příjezdu'),
            "departure": ('Místo srazu'),
            "arrival": ('Místo ukončení'),
            "notes": ('Co s sebou?'),
            "capacity": ("Maximální počet účastníků"),
            "price":("Celková cena/Vstupné"),
            "description":("Detailnější popis akce a její průběh"),
            "travel":("Vlastní doprava")
        }
        widgets={
            "organizedBy":forms.TextInput(attrs= {'class':'form-control','readonly':'readonly'}),
            'event_type': forms.Select(attrs={'class':'form-control'}, choices=Event.EVENT_TYPES),
            "name": forms.TextInput(attrs={'class':'form-control form-control-lg'}),
            "destination": forms.TextInput(attrs={'class':'form-control form-control-lg'}),
            "meeting": DateTimeInput(attrs={'class':'form-control','type': 'datetime-local', 'format': '%Y-%m-%dT%H:%M'}),
            'ending': DateTimeInput(attrs={'class':'form-control','type': 'datetime-local', 'format': '%Y-%m-%dT%H:%M'}),
            "departure": forms.TextInput(attrs={'class':'form-control'}),
            "arrival": forms.TextInput(attrs= {'class':'form-control'}),
            "notes": forms.Textarea(attrs= {"class":"form-control","rows":"3"}),
            "capacity": forms.NumberInput(attrs={'class': 'form-control','value':30, 'min': 0, 'max': 100}),
            "price": forms.NumberInput(attrs={'class': 'form-control','value':0, 'min': 0, 'max':100000}),
            "description": forms.Textarea(attrs= {"class":"form-control","rows":"3"}),
            "travel":forms.CheckboxInput(attrs={'class':'form-check-input','id':'checkbox'}),
        }

class EventEditForm(ModelForm):
    eventId = forms.CharField(widget=forms.TextInput(attrs={'id': 'eventId', "class":"invis"}))
    class Meta:
        model = Event
        fields = ('organizedBy','eventId','event_type','name', 'destination', 'meeting', 'ending', 'departure', 'arrival', 'notes','capacity','travel','price','description')
        labels={
            "event_type":('Typ akce'),
            "name": ('Název Události'),
            "destination": ('Cíl cesty/Místo konání'),
            "meeting": ('Datum a čas srazu'),
            "ending": ('Datum a čas příjezdu'),
            "departure": ('Místo srazu'),
            "arrival": ('Místo ukončení'),
            "notes": ('Co s sebou?'),
            "capacity": ("Maximální počet účastníků"),
            "price":("Celková cena/Vstupné"),
            "description":("Detailnější popis akce a její průběh"),
            "travel":("Vlastní doprava")
        }
        widgets={
            'organizedBy':forms.TextInput(attrs={'class':'form-control'}),
            'event_type': forms.Select(attrs={'class':'form-control',}, choices=Event.EVENT_TYPES),
            "name": forms.TextInput(attrs={'class':'form-control form-control-lg'}),
            "destination": forms.TextInput(attrs={'class':'form-control form-control-lg'}),
            "meeting": DateTimeInput(attrs={'class':'form-control','type': 'datetime-local', 'format': '%Y-%m-%dT%H:%M'}),
            'ending': DateTimeInput(attrs={'class':'form-control','type': 'datetime-local', 'format': '%Y-%m-%dT%H:%M'}),
            "departure": forms.TextInput(attrs={'class':'form-control'}),
            "arrival": forms.TextInput(attrs= {'class':'form-control'}),
            "notes": forms.Textarea(attrs= {"class":"form-control","rows":"3"}),
            "capacity": forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'max': 100}),
            "price": forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'max':100000}),
            "description": forms.Textarea(attrs= {"class":"form-control","rows":"3"}),
            "travel":forms.CheckboxInput(attrs={'class':'form-check-input','id':'checkbox'}),
        }
class EventCancelForm(forms.Form):  # Use forms.Form instead of forms.ModelForm
    event_id = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "readonly": True}),
        label="Event ID"
    )
    sendMail = forms.BooleanField(
        label='Ano, opravdu chci informavat všechny přihlášené o zrušení tété akce',
        initial=True,
        required=True,
        widget=forms.CheckboxInput(attrs={"class": ""})
    )
    reason = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": "4"}),
        label="Zpráva pro přihlášené: Akce se ruší z důvodu ...",
        required=True,
    )

BcWork/templates/tags/mains/accountDataChange.html
{% extends "tags/foundations/LoggedUserFoundation.html" %}
{%block main%}

    <div class="content">
    {% block Content %}
    <div class="profile" id="Profile">
        <h1>Upravit kontaktní údaje</h1>
        <br>
        {% for message in messages %}
        <p><b>{{message}}</b></p>
        {% endfor %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="id_mobile1">Telefon na zákonného zástupce</label>
                  {{form.mobile1}}
                </div>
                <div class="form-group col-md-6">
                  <label for="id_mobile2">Záložní telefon</label>
                  {{form.mobile2}}
                </div>
              </div>
              <div class="form-group">
                <h2>Kontaktní údaje na Rodiče</h2>
                <label for="inputAddress">Adresa</label>
                {{form.addres1}}
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="inputCity">Město</label>
                  {{form.city1}}
                </div>
                <div class="form-group col-md-4">
                  <label for="inputState1">Stát</label>
                  {{form.state1}}
                </div>
                <div class="form-group col-md-2">
                  <label for="inputZip">PSČ</label>
                  {{form.psc1}}
                </div>
              </div>
              <div class="form-group">
                <h2>Kontaktní údaje na druhého Rodiče</h2>
                <label for="inputAddress">Adresa</label>
                {{form.addres2}}
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="inputCity">Město</label>
                  {{form.city2}}
                </div>
                <div class="form-group col-md-4">
                  <label for="inputState2">Stát</label>
                  {{form.state2}}
                </div>
                <div class="form-group col-md-2">
                  <label for="inputZip">PSČ</label>
                  {{form.psc2}}
                </div>
              </div>
            <input type="submit" class="btn btn-primary" value="Uložit změny">
        </form>

        
    </div>
    {% endblock %}
</div>
{% endblock %}

BcWork/templates/tags/mains/accountRegister.html
{% extends "tags/foundations/notLoggedFoundation.html" %}
{%block main%}
<main>
    <div class="banner">
    
    </div>
    
    <div class="login">
        <h1>Zaregistruj se</h1>
    <form action="{% url 'account:newAccount'%}" method="post" class="logging">
        <h2>Krok 2.</h2>
        {% csrf_token %}
        <div class="userform">
              <input type="text" class="form-control" placeholder="{{username}}"readonly>
              <div style="display:none">{{form.user}}</div>
          </div>
        <div class="formRow ">
          <div class="form-502100 extraMobSpace">
            <label for="{{form.mobile1.id_for_label}}">{{form.mobile1.label}}</label>
            {{form.mobile1}}
          </div>
            <div class="form-502100 extraMobSpace">
              <label for="{{form.mobile2.id_for_label}}">{{form.mobile2.label}}</label>
              {{form.mobile2}}
          </div>
        </div>
        <div class="formRow w-100">
          <div class="form-group address">
            <label for="{{form.addres1.id_for_label}}">{{form.addres1.label}}</label>
            {{form.addres1}}
        </div>
            <div class="form-group city">
              <label for="{{form.city1.id_for_label}}">{{form.city1.label}}</label>
              {{form.city1}}
            </div>
            <div class="form-group psc ">
              <label for="{{form.psc1.id_for_label}}">{{form.psc1.label}}</label>
              {{form.psc1}}
            </div>
          </div>
        {% for message in messages %}
        <p><b>Chyba při registraci: </b>{{message}}</p>
        {% endfor %}
        <input type="submit" class="btn btn-primary" value="Registrovat"><br>
    </form>
    <br>
    </div>
    
</main>
{% endblock %}

BcWork/templates/tags/mains/addMember.html
{% extends "tags/foundations/LoggedUserFoundation.html" %}
{%block main%}
    <div class="content">
    {% block Content %}
    <div class="card border-success" style="max-width: 96%;min-height:40vh;">
        <div class="card-header bg-transparent border-success"><h2>Přidejsi si členy pod tento účet</h2></div>
        <div class="card-body text-success">
            <form method="post" action='/addMember'>
                {% csrf_token %}
                <label for="member_id">Vyber členy, kteří mají zaplaceno, ale nejsou zatím přiřazeni k žádné účtu </label>
                <select  class="form-control form-control-lg w-100" name="member_id" id="member_id">
                  {% for member in available_members %}
                    <option value="{{ member.id }}">{{ member.jmeno }} {{ member.surname }}</option>
                  {% endfor %}
                </select><br>
                <label for="born">Abychom si byli jistí, že myslíme stejného člena, zadejte datum narození</label>
                <input type="date" class="form-control" id="born" name="born">
                <br>
                <button type="submit" class="btn btn-success">Přidat</button>
              </form>
        </div>
        <div class="card-footer bg-transparent border-success"><h4>Nenašli jste člena v seznamu členů? Přidejte ho ručně. </h4>
            <a href="/createMemeber"><button class="btn btn-primary">Vytvořit nového člena</button></a></div>
      </div>
    {% endblock %}
</div>
{% endblock %}

BcWork/templates/tags/mains/allMembers.html
{% extends "tags/foundations/LoggedUserFoundation.html" %}
{%block main%}
{% load static %}
    <div class="content">
        {% block Content %}
            <div class="profile" id="Profile">    
               <h1>Všichni členové a jejich účty</h1>
               <div class="outerCard">
                    <div class="full-line">
                    <a class="btn btn-primary w-100" data-toggle="collapse" href="#Members" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">
                        <i class="fa-solid fa-circle-chevron-up"></i> Přehled všech členů oddílu
                    </a>
                    </div>
                  <div class="innerCardBody">
                    <div class="collapse height" id="Members">
                      <div class="card card-body">
                        <ul class="list-group list-group-flush">
                            {%for m in members%}
                                <li class="list-group-item"><p>{{m.name}}</p><p>{{m.born}}</p><p>{{m.phone}}</p><p><a href="{% url "account:memberDetail" m.id %}">Více info</a></p></li>
                            {% endfor %}
                          </ul>
                      </div>
                    </div>
                  </div>
               </div>
               <div class="outerCard">
                    <div class="full-line">
                    <a class="btn btn-primary w-100" data-toggle="collapse" href="#Events" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">
                        <i class="fa-solid fa-circle-chevron-up"></i> Všechny naše akce
                    </a>
                    </div>
                  <div class="innerCardBody">
                    <div class="collapse height" id="Events">
                      <div class="card card-body">
                        <ul class="list-group list-group-flush">
                            {%for e in events%}
                                <li class="list-group-item"><p><h5>{{e.name}}</h5></p><p>{{e.meeting}} - {{e.ending}}</p><br><p><a href="{% url 'event:details' e.id %}">Více info</a></p><br><p><a href="{% url "account:sendEmail" 5 e.id %}" type="button" class="btn btn-dark">Upozornit přihlášené, že se akce blíží</a><br> <br><a href="{% url "account:sendEmail" 6 e.id %}" type="button" class="btn btn-danger">Upozornit nepřihlášené, že je poslední možnost přihlášení</a></p></li>
                            {% endfor %}
                          </ul>
                      </div>
                    </div>
                  </div>
               </div>
            </div>
        {% endblock %}
    </div>
{% endblock %}

BcWork/templates/tags/mains/contacts.html
{% extends "tags/foundations/LoggedUserFoundation.html" %}
{%block main%}
{% load static %}
    <div class="content">
        {% block Content %}
            <div class="profile" id="Profile">    
               <h1>Důležité kontakty na naše vedoucí</h1>
               <div class="contact-texts">
                    <div class="card" style="width: 18rem;">
                        <img src="{% static 'img/Kuderova.jpg' %}" class="card-img-top" alt="Hlavní vedoucí">
                        <div class="card-body">
                            <h5 class="card-title">Kateřina Kuderová<br>"Kapitánka"</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Hlavní vedoucí</h6>
                            <p class="card-text">
                                Vaše dotazy spojené s administrativou a financemi směřujte prosím ke mně.<br>
                                <br>
                                Kuderova@seznam.cz<br>
                                +420 111 222 333<br>
                            </p>
                        </div>
                    </div>
                
                    <div class="card" style="width: 18rem;">
                        <img src="{% static 'img/charouzd.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title">Filip Charouzd<br>"Otes"</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Zástupce hlavní vedoucí</h6>
                        <p class="card-text">
                            Vaše dotazy spojené s oraganizací akcí nebo technické dotazy směřujte prosím ke mně.<br>
                            <br>
                            Charouzd.f@seznam.cz<br>
                            +420 702 210 101
                            </p>
                        </div>
                    </div>
               </div>
               <br>
               <div class="mail-form">
               <h2>Nevíš komu bys měl napsat?</h2>
               <h4>Napiš nám přímo tady a my ti odpovíme hned, jak to bude možné.</h4><br> 
                
               <form  method="post" action="">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.subject.id_for_label }}">Předmět:</label><br>
                        {{ form.subject }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.text.id_for_label }}">Tvoje zpráva:</label><br>
                        {{ form.text }}
                    </div>
                    <div class="send-btn"><button type="submit" class="btn btn-lg btn-primary"><i class="fa-solid fa-paper-plane" style="color: #ffffff;"></i> Odeslat zprávu</button></div>
                </form>
            </div>
        {% endblock %}
    </div>
{% endblock %}

BcWork/templates/tags/mains/login.html
{% extends "tags/foundations/notLoggedFoundation.html" %}
{%block main%}
<main>
    <div class="banner">
    
    </div>
    
    <div class="login">
        <h1>Obnov si heslo</h1>
        <form method="post" class="resetPasswsd">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Obnovit heslo">
        </div>
            {% for message in messages %}
        <p><b>Chyba při zasílání obnovovacího odkazu: </b>{{message}}</p>
        {% endfor %}

</form>
    
    </div>
    
</main>
{% endblock %}

BcWork/templates/tags/mains/registerUser.html
{% extends "tags/foundations/notLoggedFoundation.html" %}
{%block main%}
<main>
    <div class="banner">
    
    </div>
    
    <div class="login">
        <h1>Zaregistruj se</h1>
    <form action="{% url "account:signUp" %}" method="post" class="logging">
        <h2>Krok 1.</h2>
        {% csrf_token %}
            {% for field in form %}
        <p>{{ field.label_tag }} {{ field }} {{ field.help_text }}</p>
        <br>
    {% endfor %}
        {% for message in messages %}
        <p>{{message}}</p><br>
        {% endfor %}
        <input type="submit" class="submit btn-primary" value="Registrovat">
        <p>Už máš účet? <a href="/login">Přihlaš se</a></p>
        <p>Zapomněl jsi heslo? <a href="password_reset">Zapomenuté heslo</a></p>
    </form>
    </div>
    
</main>
{% endblock %}

BcWork/templates/tags/mains/removeMember.html
{% extends "tags/foundations/LoggedUserFoundation.html" %}
{%block main%}
    <div class="content">
    {% block Content %}
    <h2>Odeber členy tohoto účtu</h2><br>
    
  <form class="remMem" method="post" action="{% url "account:removeMemeber" %}">
    {% csrf_token %}
    <div class="split1 remMem">
      <label for="member_id"><h4>Zvolte člena:</h4></label>
      <select class="form-control " name="member_id" id="member_id">
        {% for member in available_members %}
          <option value="{{ member.id }}">{{ member.jmeno }} {{ member.surname }}</option>
        {% endfor %}
      </select>
  </div>
    <label for"Atom"><h4>Napište osobní číslo člena pro potvrzení</h4><label><br>
    <input  class="form-control" type="text" id="Atom" name="Atom"><br>
    <button class="btn btn-danger" type="submit">Odebrat zvoleného člena</button>
  </form>
    {% endblock %}
</div>
{% endblock %}