BcWork/Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView
from Litomici_memeber_system import settings as STS

app_name = 'account'
urlpatterns = [
    #administration
    path("showMembers&Accounts",views.showMembers, name="showMembers"), # type: ignore
    path("semberDetail/<str:member_id>",views.memberDetail,name="memberDetail"), # type: ignore
    path("payment",views.seeMoney,name="payment"),
    path("economy",views.unpayed_payments,name="economy"),
    path("bankTransactions",views.bank_transactions,name="bankTransactions"),
    path("payed",views.payed_payments,name="payed"),
    path("payments",views.payments,name="payments"),
    path("notify2pay/<str:account_id>",views.notify2pay,name="notify2pay"),
    path("addMoney2pay/<str:account_id>",views.addMoney2pay,name="need2pay"),
    path("manualPayment",views.manual_payment,name="manualP"),
    path("maunalDown",views.download_pdf,name="getManual"),
    #sending an email
    path("sendNotification/<int:action_id>/<int:event_id>",views.sendNotification,name="sendEmail"),#type: ignore
    path("sendMsg",views.sendMessage,name="sendMSG"),#simple message from user
    path("addNewUser",views.addUserToAccount,name="addNewUser"),#adding new user to account # type: ignore
    path("setPassword/<str:token>/",views.invitedUser,name="setPasswd"),
    #account operations
    path("account",views.userIn, name="logged"),
    path("profileInfo",views.userData, name="profile"),
    path("removeMember",views.removeMember,name="removeMemeber"),
    path("addMember",views.add_member_to_account,name="addMember"),
    path("changeData", views.changeData, name="changeData"),
    #creating new entity
    path("register",views.signUp, name="signUp"),
    path('newAccount',views.NewAccount, name='newAccount'),
    path("addEvent",views.userData, name="addEvent"),
    path("createMemeber",views.newMember,name="newMember"),
    #loging
    path("login",views.signIn, name="login"),
    path("logout",LogoutView.as_view(next_page=STS.LOGOUT_REDIRECT_URL), name="logout"),
    #password reset 
    path('password_reset/', PasswordResetView.as_view(template_name='registration/resetPass.html',from_email='turistaklitomici@gmail.com', html_email_template_name='registration/password_reset_email.html',email_template_name='registration/password_reset_email.html',success_url="done"), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='registration//password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #errors
    path("",views.signIn, name="404"),
    #development only 
    # path("test",views.tester,name="test"),
    # path("testF",views.testF,name="testF"),
    

]

BcWork/Events/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView


app_name = 'event'
urlpatterns = [
    path("listAll/<int:event_id>/",views.listAll,name="listAll_id_add"),
    path("listAll",views.listAll,name="listAll"),
    path("details/<int:event_id>/",views.details,name="details"),
    path("listCamps",views.listCamps,name="listCamps"),
    path("campRegister/<int:event_id>",views.campReg,name="campRegister"), # type: ignore
    path("eventTool",views.eventActions,name="tool"), # type: ignore
    path("eventTool/create",views.eventActionsCreate,name="tool-create"),
    path("eventTool/edit",views.eventActionEdit,name="tool-edit"),
    path("eventTool/attendance",views.eventActionAttendace,name="tool-attendace"),
    path("eventTool/attendanceOfEvent/<int:event_id>/",views.eventActionAttendace2Event,name="tool-attendace2Event"),
    path("eventTool/cancel",views.eventActionCancle,name="tool-cancel"),
    path("eventTool/cancelOfEvent/<int:event_id>",views.cancelingOfEvent,name="tool-cancelOfEvent"),#type: ignore
]

BcWork/Litomici_memeber_system/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from Accounts import urls
from Events import urls

urlpatterns = [
    path('admin/', admin.site.urls,),
    path("",include("Accounts.urls")),
    path("event/",include("Events.urls")),
]

BcWork/templates/tags/foundations/LoggedUserFoundation.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../static/css/account.css">
        <link rel="stylesheet" href="../static/css/general.css">
        <link rel="stylesheet" href="../static/css/account-navbar.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
        <script src="https://kit.fontawesome.com/4e7b80b1e6.js" crossorigin="anonymous"></script>
        <script src="https://smtpjs.com/v3/smtp.js"></script>
        <link rel="stylesheet" href="{% static 'css/general.css'%}">
        <link rel="stylesheet" href="{% static 'css/account.css'%}">
        <link rel="stylesheet" href="{% static 'css/account-navbar.css'%}">
        <link rel="stylesheet" href="{% static 'css/logged-responsive.css'%}">
        {% comment %} <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script> {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"></script>

    </head>
    <body>
        <header>
            <a href="{% url "account:logged" %}"><img src="{% static 'img/whiteLogoNoBG.png' alt="logo v bílé barvě"%}"></a>
            <div class="headline"><h1>Litomcamp</h1>
                </div>
        </header>
        <main>
            <div class="slimScreen">
            {% include "tags/pageComponents/topNavbar.html" %}
            
            </div>
            <table class="main-tab">
                <tr>
                <td class="main-coll-nav wideScreen ">
                    {%include "tags/pageComponents/sideNavbar.html"%}
                </td>
                <td rowspan="2" class="main-coll-cont">
                    {% include "tags/pageComponents/popMSG.html" %}
                    {% block main %}
                    {% endblock %}
                </td>
                </tr>
                <tr>
                    <td class="main-coll-Lout wideScreen">
                        <div class="logout">
                            <a href="{% url "account:logout" %}"><button type="button" class="btn btn-light">Odhlásit se</button></a>
                        <div>
                    </td>
                </tr>
            </table>
        </main>
        <footer>
            <div>
                <h3>Turistický oddíl mládeže Čr LITOMÍCI č.oddílu: 21205</h3><br>
                <p>
                    Dukelské kasárny budova č. 24, Na Vinici<br>
                    412 01 Litoměřice, Česká republika, EU<br>
                    <br>
                    tel. +420 702 210 101<br>
                    tel. +420 776 469 914<br>
                    turistaklitomici@gmail.com
                </p>
                <p>Version 1.1.2<br>Released on 1.4.2024<br><a href="{% url "account:getManual" %}" target="_blank"> Návod k obsluze </a></p>
            </div>
        </footer>
    </body>
</html>

BcWork/templates/tags/foundations/loggedUserFoundation.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="../static/css/account.css">
        <link rel="stylesheet" href="../static/css/general.css">
        <link rel="stylesheet" href="../static/css/account-navbar.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
        <script src="https://kit.fontawesome.com/4e7b80b1e6.js" crossorigin="anonymous"></script>
        <script src="https://smtpjs.com/v3/smtp.js"></script>
        <link rel="stylesheet" href="{% static 'css/general.css'%}">
        <link rel="stylesheet" href="{% static 'css/account.css'%}">
        <link rel="stylesheet" href="{% static 'css/account-navbar.css'%}">
        {% comment %} <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script> {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"></script>

    </head>
    <body>
        <header>
            <img src="{% static 'img/whiteLogoNoBG.png' alt="logo v bílé barvě"%}">
            <div class="headline"><h1>Litomcamp</h1>
                </div>
        </header>
        <main>
            <table class="main-tab">    
                <tr>
                <td class="main-coll-nav">
                    {%include "tags/pageComponents/sideNavbar.html"%}
                </td>
                <td rowspan="2" class="main-coll-cont">
                    {% include "tags/pageComponents/popMSG.html" %}
                    {% block main %}
                    {% endblock %}
                </td>
                </tr>
                <tr>
                    <td class="main-coll-Lout">
                        <div class="logout">
                            <a href="/logout"><button type="button" class="btn btn-light">Odhlásit se</button></a>
                        <div>
                    </td>
                </tr>
            </table>
        </main>
        <footer>
            <div>
                <h3>Turistický oddíl mládeže Čr LITOMÍCI č.oddílu: 21205</h3><br>
                <p>
                    Dukelské kasárny budova č. 24, Na Vinici<br>
                    412 01 Litoměřice, Česká republika, EU<br>
                    <br>
                    tel. +420 702 210 101<br>
                    tel. +420 776 469 914<br>
                    turistaklitomici@gmail.com
                </p>
            </div>
        </footer>
    </body>
</html>

BcWork/templates/tags/foundations/notLoggedFoundation.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/general.css' %}">
        <link rel="stylesheet" href="{% static 'css/login.css'%}">
        <link rel="stylesheet" href="{% static 'css/notLogged-responsive.css'%}">
        
        
    </head>
    <body>
        <header>
            <a href="{% url "account:login" %}"><img src="{% static 'img/whiteLogoNoBG.png' %}"></a><br>
            <div class="headline"><h1>Litomcamp</h1><br>
            <h2>Rozvíjej své dovednosti naplno</h2></div>
        </header>
        {% block main %}{% endblock  %}
        <footer>
            <div>
                <h3>Turistický oddíl mládeže Čr LITOMÍCI č.oddílu: 21205</h3><br>
                <p>
                    Dukelské kasárny, Na Vinici<br>
                    412 01 Litoměřice, Česká republika, EU<br>
                    <br>
                    tel. +420 702 210 101<br>
                    tel. +420 776 469 914<br>
                    turistaklitomici@gmail.com
                </p>

                <p>Version 1.1.2<br>
                   Released on 1.4.2024<br>
                   <a href="{% url "account:getManual" %}" target="_blank"> Návod k obsluze </a>
            </p>
            </div>
        </footer>

    </body>
</html>

BcWork/templates/tags/foundations/notLoggedfoundation.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/general.css' %}">
        <link rel="stylesheet" href="{% static 'css/login.css'%}">
        
    </head>
    <body>
        <header>
            <a href="login"><img src="{% static 'img/whiteLogoNoBG.png' %}"></a><br>
            <div class="headline"><h1>Litomcamp</h1><br>
            <h2>Rozvíjej své dovednosti naplno</h2></div>
        </header>
        {% block main %}{% endblock  %}
        <footer>
            <div>
                <h3>Turistický oddíl mládeže Čr LITOMÍCI č.oddílu: 21205</h3><br>
                <p>
                    Dukelské kasárny, Na Vinici<br>
                    412 01 Litoměřice, Česká republika, EU<br>
                    <br>
                    tel. +420 702 210 101<br>
                    tel. +420 776 469 914<br>
                    turistaklitomici@gmail.com
                </p>
            </div>
        </footer>
        
        <script src="" async defer></script>
    </body>
</html>