BcWork/Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView
from Litomici_memeber_system import settings as STS

app_name = 'account'
urlpatterns = [
    #administration
    path("showMembers&Accounts",views.showMembers, name="showMembers"), # type: ignore
    path("semberDetail/<str:member_id>",views.memberDetail,name="memberDetail"), # type: ignore
    path("payment",views.seeMoney,name="payment"),
    path("economy",views.unpayed_payments,name="economy"),
    path("bankTransactions",views.bank_transactions,name="bankTransactions"),
    path("payed",views.payed_payments,name="payed"),
    path("payments",views.payments,name="payments"),
    path("notify2pay/<str:account_id>",views.notify2pay,name="notify2pay"),
    path("addMoney2pay/<str:account_id>",views.addMoney2pay,name="need2pay"),
    path("manualPayment",views.manual_payment,name="manualP"),
    path("maunalDown",views.download_pdf,name="getManual"),
    #sending an email
    path("sendNotification/<int:action_id>/<int:event_id>",views.sendNotification,name="sendEmail"),#type: ignore
    path("sendMsg",views.sendMessage,name="sendMSG"),#simple message from user
    path("addNewUser",views.addUserToAccount,name="addNewUser"),#adding new user to account # type: ignore
    path("setPassword/<str:token>/",views.invitedUser,name="setPasswd"),
    #account operations
    path("account",views.userIn, name="logged"),
    path("profileInfo",views.userData, name="profile"),
    path("removeMember",views.removeMember,name="removeMemeber"),
    path("addMember",views.add_member_to_account,name="addMember"),
    path("changeData", views.changeData, name="changeData"),
    #creating new entity
    path("register",views.signUp, name="signUp"),
    path('newAccount',views.NewAccount, name='newAccount'),
    path("addEvent",views.userData, name="addEvent"),
    path("createMemeber",views.newMember,name="newMember"),
    #loging
    path("login",views.signIn, name="login"),
    path("logout",LogoutView.as_view(next_page=STS.LOGOUT_REDIRECT_URL), name="logout"),
    #password reset 
    path('password_reset/', PasswordResetView.as_view(template_name='registration/resetPass.html',from_email='turistaklitomici@gmail.com', html_email_template_name='registration/password_reset_email.html',email_template_name='registration/password_reset_email.html',success_url="done"), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='registration//password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    #errors
    path("",views.signIn, name="404"),
    #development only 
    # path("test",views.tester,name="test"),
    # path("testF",views.testF,name="testF"),
    

]

BcWork/Events/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth.views import LogoutView,PasswordResetDoneView,PasswordResetView,PasswordResetCompleteView,PasswordResetConfirmView


app_name = 'event'
urlpatterns = [
    path("listAll/<int:event_id>/",views.listAll,name="listAll_id_add"),
    path("listAll",views.listAll,name="listAll"),
    path("details/<int:event_id>/",views.details,name="details"),
    path("listCamps",views.listCamps,name="listCamps"),
    path("campRegister/<int:event_id>",views.campReg,name="campRegister"), # type: ignore
    path("eventTool",views.eventActions,name="tool"), # type: ignore
    path("eventTool/create",views.eventActionsCreate,name="tool-create"),
    path("eventTool/edit",views.eventActionEdit,name="tool-edit"),
    path("eventTool/attendance",views.eventActionAttendace,name="tool-attendace"),
    path("eventTool/attendanceOfEvent/<int:event_id>/",views.eventActionAttendace2Event,name="tool-attendace2Event"),
    path("eventTool/cancel",views.eventActionCancle,name="tool-cancel"),
    path("eventTool/cancelOfEvent/<int:event_id>",views.cancelingOfEvent,name="tool-cancelOfEvent"),#type: ignore
]

BcWork/Litomici_memeber_system/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from Accounts import urls
from Events import urls

urlpatterns = [
    path('admin/', admin.site.urls,),
    path("",include("Accounts.urls")),
    path("event/",include("Events.urls")),
]

BcWork/Events/models.py
from email.policy import default
from tokenize import blank_re
from unittest.util import _MAX_LENGTH
import uuid
from django.db import models
from Accounts.models import member

class Event(models.Model):
    EVENT_TYPES = [
        ('vylet', 'Výlet'),
        ('tabor_vyprava', 'Tábor/Výprava'),
        ('oddilovka', 'Oddílovka'),
        ('akce_pro_verejnost', 'Akce pro veřejnost'),
        ('jine', 'Jiné'),
    ]
    organizedBy=models.CharField(default="turistaklitomici@gmail.cz",max_length=100)
    event_type = models.CharField(max_length=50, choices=EVENT_TYPES, default='vylet')#druh akce
    name=models.CharField(max_length=80)#jméno události
    destination=models.CharField(max_length=80)#cílová destinace
    meeting=models.DateTimeField()#den a čas odjezdu
    ending=models.DateTimeField(blank=True)# den a čas příjezdu
    departure=models.CharField(max_length=100)# místo odjezdu
    arrival=models.CharField(default="Včas upřesníme", max_length=100, blank=True)#místo příjezdu
    notes=models.CharField(default="Dobrou náladu", blank=True,max_length=500)# s sebou a poznámky
    assigned=models.ManyToManyField(member, related_name=("assigned"), blank=True)# přihlášení
    attendance=models.ManyToManyField(member, related_name=("attendance"), blank=True)# zúčastnění
    price=models.IntegerField(default=0)# cena za jednoho
    capacity=models.IntegerField(default=50,blank=True)#kolik se lidí se může zapsat
    description=models.CharField(blank=True,max_length=500,default=" ",)#bližší popis akce
    travel=models.BooleanField(blank=True,default=True)#způsob dopravy => společně/po vlastní ose
    objects = models.Manager()
    def __str__(self):
        return self.name +" ("+ self.destination+" "+self.event_type+")"

BcWork/templates/tags/pageComponents/ManualPayment.html
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var form = document.getElementById('myForm');
        var input1 = document.getElementById('additionalInput1');
        var input2 = document.getElementById('additionalInput2');
    
        form.addEventListener('change', function() {
            if (document.querySelector('input[name="paymentType"]:checked').value === 'option1') {
                input1.style.display = 'block';
                input2.style.display = 'none';
            } else if (document.querySelector('input[name="paymentType"]:checked').value === 'option2') {
                input1.style.display = 'none';
                input2.style.display = 'block';
            }
        });
    });
</script>
<form method="post" action="{% url "account:manualP" %}" id="myForm">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-4">
          <label for="inputCity">Částka</label>
          <input type="number" step="0.1" value="0.0" min="0" class="form-control" id="inputCity" name="amount" required>
        </div>
        <div class="form-group col-md-2">
            <label for="inputCity"><br> </label>
            <input type="text" class="form-control" readonly value="Kč" id="inputZip" required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputState">Zaplatil</label>
          <select id="inputState" class="form-control" name="acc" required>
            <option placeholder>Vyberte</option>
            {% for a in accounts %}
                <option value="{{a.id}}">
                    {{a.user.username}}-
                    {% for m in a.member.all %}
                        {{m.jmeno}} {{m.surname}},
                        {% endfor %}
                </option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="form-row">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="paymentType" id="Radio1" value="option1">
            <label class="form-check-label" for="Radio1">Platba na účet</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="paymentType" id="Radio2" value="option2">
            <label class="form-check-label" for="Radio2">Platba v hotovosti</label>
          </div>
        </div>  
        <div id="additionalInput1" style="witdh:100%; display: none;">
            <h6>Podrobnosti platby</h6>
            <div class="form-group">
                <label for="From">Z účtu</label>
                <input type="text" class="form-control" id="From" aria-describedby="from" name="from">
                <small id="from" class="form-text text-muted">zadejte číslo s účtu i s lomítkem. např.: 123456789/0123</small>
              </div>
            <div class="form-group">
                <label for="VS">Variabilní symbol</label>
                <input type="text" class="form-control" id="VS" maxlength="10" name="Vs" pattern="[0-9]*" aria-describedby="vs">
                <small id="vs" class="form-text text-muted">VS nebo číslo, pro identifikaci plátce</small>
            </div>
            <div class="form-group">
                <label for="Date">Datum platby</label>
                <input type="date" class="form-control" id="Date" name="payed" aria-describedby="date">
                <small id="date" class="form-text text-muted">datum platby ve fromátu měsíc/den/rok</small>
            </div>
            <div class="form-group">
                <label for="Tid">Číslo transakce</label>
                <input type="text" class="form-control" id="Tid" name="nmT" aria-describedby="tid">
                <small id="tid" class="form-text text-muted">Ve výpisu jako "Kód transakce"</small>
            </div>
        </div>
        
        <div id="additionalInput2" style="display: none;">
            <div class="form-group">
                <label for="Date">Datum platby</label>
                <input type="date" class="form-control" id="Date" name="payedOn" aria-describedby="date">
                <small id="date" class="form-text text-muted">datum platby ve fromátu měsíc/den/rok</small>
            </div>
            <div class="form-group">
                <label for="PB">kdo a kde platil</label>
                <input type="text" maxlength="30" class="form-control" id="PB" name="payedBy" placeholder="Rodič na nádraží" aria-describedby="pb">
                <small id="pb" class="form-text text-muted">max 30 znaků</small>
            </div>
            <div class="form-group">
                <label for="Date">Kdo převzal platbu(narození)</label>
                <input type="text" class="form-control" id="VS" name="VsP" placeholder="00ddmmyyyy" maxlength="10" pattern="[0-9]*" aria-describedby="vs">
                <small id="vs" class="form-text text-muted">Kápo=0015051968 <br>Otes=0016092000<br>Honza=0015042001<br>Kšilt=0023112003<br></small>

            </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Založit platbu</button>
</form>

BcWork/templates/tags/pageComponents/actionAttendaceForm.html
        <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Datum</th>
            <th scope="col">Jméno akce</th>
            <th class="capPadding" scope="col">Kapacita</th>
            <th class="wideScreen" scope="col">Detaily</th>
            <th scope="col">Docházka</th>
          </tr>
        </thead>
        <tbody>
          {% for event in events %}
            <tr>
              <th scope="row">{{ event.meeting|date:"F d, Y H:i" }}</th>
              <td>{{ event.name }}</td>
              <td class="capPadding">{{event.assigned.all|length }}/{{event.capacity}}</td>
              <td class="wideScreen"><a href="{% url "event:details" event.id %}">Info</td>
                <td> <a href="{% url "event:tool-attendace2Event" event.id %}"  type=button class="btn btn-primary" type="button">
                  Udělat docházku
                </a>
                </td>
            </tr>
          {% endfor %}
          </tbody>
      </table>

BcWork/templates/tags/pageComponents/actionCancelForm.html
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Datum</th>
        <th scope="col">Jméno akce</th>
        <th class="capPadding" scope="col">Kapacita</th>
        <th class="wideScreen" scope="col">Detaily</th>
        <th scope="col">Akce</th>
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
        <tr>
          <th scope="row">{{ event.meeting|date:"F d, Y H:i" }}</th>
          <td>{{ event.name }}</td>
          <td class="capPadding">{{event.assigned.all|length }}/{{event.capacity}}</td>
          <td class="wideScreen"><a href="{% url "event:details" event.id %}">Info</td>
            <td> <a href="{% url "event:tool-cancelOfEvent" event.id %}"  type=button class="btn btn-primary" type="button">
              Zrušit
            </a>
            </td>
        </tr>
      {% endfor %}
      </tbody>
  </table>

BcWork/templates/tags/pageComponents/actionCreationForm.html
<form method="post" action="{% url "event:tool-create" %}">
    {% csrf_token %}
    <div class="form-row hiddenOF">
      <div class="form-group col-md-6">
        <label for="contact">Email na Organizátora</label><br>
        {{form.organizedBy}}
      </div>
      <div class="form-group col-md-6 ">
        <label for="{{ form.event_type.id_for_label }}">Typ akce</label>
        {{ form.event_type }}
        
      </div>
    </div>
    <div class="form-group">
        <label for="{{ form.name.id_for_label }}">Název Události</label>
        {{ form.name }}
          </div>
    <div class="form-group">
        <label for="{{ form.destination.id_for_label }}">{{ form.destination.label }}</label>
        {{ form.destination }}
    </div>
    <div class="form-row">
      <div class="form-group col-md-7">
        <label for="{{ form.departure.id_for_label }}">{{ form.departure.label }}</label>
        {{ form.departure }}
      </div>
      <div class="form-group col-md-5">
        <label for="{{ form.meeting.id_for_label }}">{{ form.meeting.label }}</label>
        {{ form.meeting }}
      </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-7">
          <label for="{{ form.arrival.id_for_label }}">{{ form.arrival.label }}</label>
          {{ form.arrival }}
        </div>
        <div class="form-group col-md-5">
          <label for="{{ form.ending.id_for_label }}">{{ form.ending.label }}</label>
          {{ form.ending }}
        </div>
        </div>
        <div class="form-group">
            <label for="{{ form.notes.id_for_label }}">{{ form.notes.label }}</label>
          {{ form.notes }}
        </div>
      <div class="form-row">
        <div class="form-group col-md-6">
            <label for="{{ form.capacity.id_for_label }}">{{ form.capacity.label }}</label>
            {{ form.capacity }}
        </div>
        <div class="form-group col-md-6">
            <label for="{{ form.price.id_for_label }}">{{ form.price.label }}</label>
            {{ form.price }}
          </div>
        
      </div>
      <div class="form-group">
        <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
      {{ form.description }}
    </div>
    <button type="submit" class="btn btn-primary">Vytvořit událost</button>
  </form>

BcWork/templates/tags/pageComponents/actionEdit.html
<form method="post" action="" id="eventEditor">
    {% csrf_token %}

    <div class="form-row">
      {{form.eventId}}
      <div class="form-group col-md-6">
        <label for="id_organizedBy">Organizátor</label><br>
        {{ form.organizedBy }}
      </div>
      <div class="form-group col-md-6">
        <label for="{{ form.event_type.id_for_label }}">Typ akce</label>
        {{ form.event_type }}
        
      </div>
    </div>
    <div class="form-group">
        <label for="{{ form.name.id_for_label }}">Název Události</label>
        {{ form.name }}
          </div>
    <div class="form-group">
        <label for="{{ form.destination.id_for_label }}">{{ form.destination.label }}</label>
        {{ form.destination }}
    </div>
    <div class="form-row">
      <div class="form-group col-md-7">
        <label for="{{ form.departure.id_for_label }}">{{ form.departure.label }}</label>
        {{ form.departure }}
      </div>
      <div class="form-group col-md-5">
        <label for="{{ form.meeting.id_for_label }}">{{ form.meeting.label }}</label>
        {{ form.meeting }}
      </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-7">
          <label for="{{ form.arrival.id_for_label }}">{{ form.arrival.label }}</label>
          {{ form.arrival }}
        </div>
        <div class="form-group col-md-5">
          <label for="{{ form.ending.id_for_label }}">{{ form.ending.label }}</label>
          {{ form.ending }}
        </div>
        </div>
        <div class="form-group">
            <label for="{{ form.notes.id_for_label }}">{{ form.notes.label }}</label>
          {{ form.notes }}
        </div>
      <div class="form-row">
        <div class="form-group col-md-6">
            <label for="{{ form.capacity.id_for_label }}">{{ form.capacity.label }}</label>
            {{ form.capacity }}
        </div>
        <div class="form-group col-md-6">
            <label for="{{ form.price.id_for_label }}">{{ form.price.label }}</label>
            {{ form.price }}
          </div>
      </div>
      <div class="form-group">
        <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
      {{ form.description }}
    </div>
    <div class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" id="customCheck1" name="notify">
      <label class="custom-control-label" for="customCheck1">Poslat zapsaným účastníkům upozornění o změnách</label>
    </div>
    <button type="submit" class="btn btn-primary">Uložit změny</button>
  </form>

BcWork/templates/tags/pageComponents/actionbarOptions.html
<div class="actionBar">
    <a href="{% url "event:tool-create"%}" role="button" class="btn btn-success">Vytvořit novou akci</a><span> |</span>
    <a href="{% url "event:tool-edit"%}"role="button" class="btn btn-warning">Upravit existující akci</a> <span> | </span>
    <a href="{% url "event:tool-attendace"%}" role="button" class="btn btn-info">Zapsat docházku</a><span> | </span>
    <a href="{% url "event:tool-cancel" %}"role="button" class="btn btn-danger">Zrušit akci</a>
</div>

BcWork/templates/tags/pageComponents/popMSG.html
<script>
    function msgShow(txt) {
      alert(txt);
    }
</script>
{% for message in messages%}
        <script>
                msgShow("{{message}}");
        </script>
{% endfor %}

BcWork/templates/tags/pageComponents/sideNavbar.html
<ul>
    <a href="{% url "account:profile" %}"><li id="nav-profile" >Profil</li></a>
    <a href="{% url "event:listAll" %}"><li id="nav-profile" >Rozvrh akcí</li></a>
    <a href="{% url "account:sendMSG" %}"><li id="nav-profile" >Kontaktuj nás</li></a>
    <a href="{% url "event:listCamps" %}"><li id="nav-camps" >Tábory</li></a>
    {% if role >= 1 %}
    <!-- for leader-->
        <a href="{% url "event:tool"%}"><li>správa akcí</li></a>
    {% endif %}
    {% if role >= 2 %}
    <!-- for econom -->
    <a href="{% url "account:economy" %}"> <li>Platby</li></a>
    {% endif %}
    {%if  role >= 3 %}
    <!-- for Admin/heads -->
    <a href="{% url "account:showMembers" %}"><li>Správa členů</li></a>
    {% endif %}
</ul>

BcWork/templates/tags/pageComponents/topNavbar.html
<ul>
    {% comment %} profile {% endcomment %}
    {% if 'profileInfo' in request.path or 'AddNewUser' in request.path or 'addMember' in request.path or 'createMemeber' in request.path or 'removeMember' in request.path or 'changeData' in request.path %}
        <a href="{% url "account:profile" %}" class="thisPage"><li id="nav-profile" ><i class="fa-solid fa-user"></i></li></a>
    {% else %}
        <a href="{% url "account:profile" %}"><li id="nav-profile" ><i class="fa-solid fa-user"></i></li></a>
    {% endif %}
    {% comment %} plán akcí {% endcomment %}
    {% if 'event/listAll' in request.path or 'event/details/' in request.path %}
    <a href="{% url "event:listAll" %}"  class="thisPage"><li id="nav-schedual" ><i class="fa-solid fa-calendar-days"></i></li></a>
    {% else %}
    <a href="{% url "event:listAll" %}"><li id="nav-schedual" ><i class="fa-solid fa-calendar-days"></i></li></a>
    {% endif %}
    {% comment %} kontakt {% endcomment %}
    {% if 'sendMsg' in request.path %}
    <a href="{% url "account:sendMSG" %}"  class="thisPage"><li id="nav-contact" ><i class="fa-solid fa-phone"></i></li></a>
    {% else %}
    <a href="{% url "account:sendMSG" %}" ><li id="nav-contact" ><i class="fa-solid fa-phone"></i></li></a>
    {% endif %}
    {% comment %} tábor {% endcomment %}
    {% if 'event/listCamps' in request.path or 'event/campRegister/' in request.path %}
    <a href="{% url "event:listCamps" %}"  class="thisPage"><li id="nav-camps" ><i class="fa-solid fa-campground"></i></li></a>
    {% else %}
    <a href="{% url "event:listCamps" %}"><li id="nav-camps" ><i class="fa-solid fa-campground"></i></li></a>
    {% endif %}

    
    {% if role >= 1 %}
    <!-- for leader-->
    {% if 'event/eventTool' in request.path%}
    <a href="{% url "event:tool"%}" class="thisPage"><li><i class="fa-solid fa-clipboard-user"></i></li></a>
    {% else %}
    <a href="{% url "event:tool"%}"><li><i class="fa-solid fa-clipboard-user"></i></li></a>
    {% endif %}
        
    {% endif %}
    {% if role >= 2 %}
    <!-- for econom -->
    <a href="{% url "account:economy" %}"><li><i class="fa-regular fa-money-bill-1"></i></li></a>
    {% endif %}
    {%if  role >= 3 %}
    <!-- for Admin/heads -->
    <a href="{% url "account:showMembers" %}"><li><i class="fa-solid fa-users-gear"></i></li></a>
    {% endif %}
    <a href="{% url "account:logout" %}"><li id="nav-out" ><i class="fa-solid fa-right-from-bracket"></i></li></a>
</ul>